# Generated by Django 4.0.5 on 2022-06-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballclubs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='edited_at',
        ),
    ]
