# Generated by Django 4.0.5 on 2022-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_remove_footballclubs_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclubs',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubs',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True),
        ),
    ]
